### ISSUE TITLE
is it correct to get a similar result as using "execution_path=hw" and "execution_path=sw" ?

### ISSUE THREAD

**Issue by happyvera1115** [intel/iaa-plugin-rocksdb#1]
Dear,
is it correct to get a similar result as using "execution_path=hw" and "execution_path=sw" ?

I expect the test result of "execution_path=hw" shall use less cpu resources, better bandwidth or lower latency.
But the results for "execution_path=hw" and "execution_path=sw" are similar.

is it the correct behavior as using iaa-plugin-rocksdb? or any setting I can modify or check?

Thanks.
ifen

my env:

> Intel(R) Xeon(R) Silver 4416+ * 1pcs
> Memory: DDR5 16GB * 8pcs
> OS: Ubuntu 23.04 6.2.0-31-generic
> IAA config [refer accel-config_list.txt for detail]

from this website "https://github.com/intel/iaa-plugin-rocksdb "

> execution_path
> "auto" (default): QPL decides whether to use the hardware or software path.
> "hw": QPL will use the IAA hardware.
> "sw": QPL will run compression/decompression in software.

SW path result:
[refer sw_path.txt for detail]
> readwhilewriting :       1.368 micros/op 2898876 ops/sec 1.380 seconds 4000000 operations;   42.9 MB/s (134153 of 1000000 found)
> Microseconds per read:
> Count: 4000000 Average: 1.3682  StdDev: 0.69
> Min: 0  Median: 0.7965  Max: 476
> Percentiles: P50: 0.80 P75: 1.34 P99: 2.36 P99.9: 2.97 P99.99: 5.53
> 

hw path result:
[refer hw_path.txt for detail]
> readwhilewriting :       1.393 micros/op 2838671 ops/sec 1.409 seconds 4000000 operations;   42.8 MB/s (137055 of 1000000 found)
> Microseconds per read:
> Count: 4000000 Average: 1.3935  StdDev: 0.64
> Min: 0  Median: 0.8242  Max: 321
> Percentiles: P50: 0.82 P75: 1.38 P99: 2.45 P99.9: 2.98 P99.99: 5.61
[sw_path.txt](https://github.com/intel/iaa-plugin-rocksdb/files/12746369/sw_path.txt)
[hw_path.txt](https://github.com/intel/iaa-plugin-rocksdb/files/12746370/hw_path.txt)
[accel-config_list.txt](https://github.com/intel/iaa-plugin-rocksdb/files/12746371/accel-config_list.txt)

**Comment by lucagiac81** [comment]
Hi, thank you for the detailed report. The runs are very short (< 2 seconds) and data is not pre-populated. Most requests are likely served from memtable, and no/little flush/compaction is triggered. In such conditions, compression/decompression doesn’t occur, and I think that’s why the HW/SW path show no difference.

- As a first step, please try running for longer time. You can use the --duration flag to run for a few minutes.
- Increasing the data size (--num flag) should also increase the amount of compression/decompression.
- You can also enable additional stats for better understanding of the results:  --benchmarks=readwhilewriting,stats --statistics

**Comment by happyvera1115** [comment]
Thank  Lucagica81 for the suggestions.
let me try them.

**Comment by happyvera1115** [comment]
Thanks Lucagica81 's suggestion..
--duration and --num are all ok to let me find the difference between HW path and SW Path..
