### ISSUE TITLE
db_bench parameters to replicate claims from "Intel Accelerators Ecosystem: An SoC-Oriented Perspective"

### ISSUE THREAD

**Issue by liam0215** [intel/iaa-plugin-rocksdb#7]
The "Intel Accelerators Ecosystem: An SoC-Oriented Perspective" paper published in ISCA 2024 mentions achieving 2x higher throughput when running db_bench over RocksDB with the IAA plugin. However, the paper doesn't mention the exact workload or parameters used. Can you please share a command I can run to replicate these results?

**Comment by lucagiac81** [comment]
This [whitepaper](https://www.intel.com/content/www/us/en/content-details/788607/intel-in-memory-analytics-accelerator-plugin-for-rocksdb-storage-engine-intel-iaa-plugin-for-rocksdb-storage-engine.html) has more details specific to RocksDB with IAA. It should be helpful.

**Comment by liam0215** [comment]
Thank you so much!
